### ISSUE TITLE
zobrazovanie hráčov patriacich do klubu (po kluknutí na konkrétny klub)

### ISSUE THREAD

**Issue by vavrova55** [TIS2016/Friesbee#22]

**Comment by mirelon** [comment]
Uz som si to rozbehal. Prve, co som vyskusal, otvoril som si klub a bol som zavaleny mnozstvom informacii o kazdom hracovi. Bud by to malo byt collapsnute, alebo zobrazene v tabulke... proste, aby som tam videl ten zoznam hracov. Myslim, ze to spada pod tuto issue.
