### ISSUE TITLE
vyriešenie platby členského

### ISSUE THREAD

**Issue by vavrova55** [TIS2016/Friesbee#29]

**Comment by mirelon** [comment]
Mate niekde zachyteny vysledok stretnutia s Marcelom? Tam to bolo zobrazene v takom diagrame, kde boli zvlast kluby a kluby_saf, ktore boli na hraca napojene cez platbu.

**Comment by mirelon** [comment]
- vyhodit percenta
- kategoria platby treba premenovat na typ_clenstva, su 3 fixne a maju atributy `nazov` a `suma` (mozte to naplnit napr. takto https://docs.djangoproject.com/en/1.10/howto/initial-data/)
  Čestné členské 0
  Zľavnené členské 8
  Plné členské 13
- Clenstvo ma atributy `hrac_id`, `klub_saf_id`, `rok`, `suma`, `datum`
- sumy su typu decimal, nie string
